org: solarnius
app: classify-serverless
service: classify-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:*"
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
            - "lambda:ListFunctions"
          Resource: "*"

plugins:
  - serverless-api-gateway-throttling
  - serverless-python-requirements

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 100
    maxConcurrentRequests: 1000
  dynamodb:
    stages:
      - dev
  pythonRequirements:
    dockerizePip: true
    dockerFile: Dockerfile

layers:
  tesseractAl2:
    path: ./compiled/amazonlinux-2
    compatibleRuntimes:
      - python3.8

functions:
  classify:
    handler: classify.handler
    timeout: 30
    events:
      - httpApi:
          path: /classify
          method: get
  tesseract-ocr:
    handler: handler.main
    runtime: python3.8
    layers:
      - { Ref: TesseractAl2LambdaLayer }

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: cnftTable
        AttributeDefinitions:
          - AttributeName: address
            AttributeType: S
        KeySchema:
          - AttributeName: address
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    treeTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: treeTable
        AttributeDefinitions:
          - AttributeName: address
            AttributeType: S
        KeySchema:
          - AttributeName: address
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
